/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Metodos.*;

import javax.swing.JOptionPane;

/**
 *
 * @author JuanPablo
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        BiseccionP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BiseccionBt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        A_BI_TF = new javax.swing.JTextField();
        B_BI_TF = new javax.swing.JTextField();
        Tol_BI_TF = new javax.swing.JTextField();
        It_BI_TF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LagrangeBt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        x1_LagrangeTf = new javax.swing.JTextField();
        y1_LagrangeTf = new javax.swing.JTextField();
        x2_LagrangeTf = new javax.swing.JTextField();
        y2_LagrangeTf = new javax.swing.JTextField();
        x3_LagrangeTf = new javax.swing.JTextField();
        y3_LagrangeTf = new javax.swing.JTextField();
        x4_LagrangeTf = new javax.swing.JTextField();
        y4_LagrangeTf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        vit_LagrangeTf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        GaussBt = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        z1_GJTf = new javax.swing.JTextField();
        z2_GJTf = new javax.swing.JTextField();
        z3_GJTf = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        x1_GJTf = new javax.swing.JTextField();
        y1_GJTf = new javax.swing.JTextField();
        x2_GJTf = new javax.swing.JTextField();
        y2_GJTf = new javax.swing.JTextField();
        x3_GJTf = new javax.swing.JTextField();
        y3_GJTf = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DerivacionBt = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        VD_Derivacion_Tf = new javax.swing.JTextField();
        y1_DerivacionTf1 = new javax.swing.JTextField();
        x1_DerivacionTf1 = new javax.swing.JTextField();
        x2_DerivacionTf1 = new javax.swing.JTextField();
        y2_DerivacionTf1 = new javax.swing.JTextField();
        x3_DerivacionTf1 = new javax.swing.JTextField();
        y3_DerivacionTf1 = new javax.swing.JTextField();
        x4_DerivacionTf1 = new javax.swing.JTextField();
        y4_DerivacionTf1 = new javax.swing.JTextField();
        x5_DerivacionTf1 = new javax.swing.JTextField();
        y5_DerivacionTf5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        IntegracionBt = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        LS_IntegracionTf2 = new javax.swing.JTextField();
        LI_IntegracionTf2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        Part_IntegracionTf3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NewtonBt = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Tol_NewtonTf = new javax.swing.JTextField();
        X0_NewtonTf = new javax.swing.JTextField();
        It_NewtonTf = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LUBt = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        x1_LUTf2 = new javax.swing.JTextField();
        y1_LUTf2 = new javax.swing.JTextField();
        x2_LUTf2 = new javax.swing.JTextField();
        y2_LUTf2 = new javax.swing.JTextField();
        x3_LUTf2 = new javax.swing.JTextField();
        y3_LUTf2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Ti1_LUTf3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Ti2_LUTf3 = new javax.swing.JTextField();
        Ti3_LUTf3 = new javax.swing.JTextField();
        z1_LUTf4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        z2_LUTf4 = new javax.swing.JTextField();
        z3_LUTf4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        y2_InterNewtonTf1 = new javax.swing.JTextField();
        x3_InterNewtonTf1 = new javax.swing.JTextField();
        y3_InterNewtonTf1 = new javax.swing.JTextField();
        x4_InterNewtonTf1 = new javax.swing.JTextField();
        y4_InterNewtonTf1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        x5_InterNewtonTf1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        y5_InterNewtonTf1 = new javax.swing.JTextField();
        x1_InterNewtonTf1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        VI_InterNewtonTf1 = new javax.swing.JTextField();
        y1_InterNewtonTf1 = new javax.swing.JTextField();
        x2_InterNewtonTf1 = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        AcercaDeMI = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodos Numericos");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Biseccion");

        BiseccionBt.setText("Calcular Biseccion");
        BiseccionBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiseccionBtActionPerformed(evt);
            }
        });

        jLabel8.setText("Punto A:");

        jLabel9.setText("Punto B:");

        jLabel10.setText("Tolerancia:");

        jLabel11.setText("Iteraciones:");

        A_BI_TF.setText(" ");
        A_BI_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BI_TFActionPerformed(evt);
            }
        });

        B_BI_TF.setText(" ");

        Tol_BI_TF.setText(" ");

        It_BI_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                It_BI_TFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BiseccionPLayout = new javax.swing.GroupLayout(BiseccionP);
        BiseccionP.setLayout(BiseccionPLayout);
        BiseccionPLayout.setHorizontalGroup(
            BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiseccionPLayout.createSequentialGroup()
                .addGroup(BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BiseccionPLayout.createSequentialGroup()
                        .addContainerGap(158, Short.MAX_VALUE)
                        .addComponent(BiseccionBt))
                    .addGroup(BiseccionPLayout.createSequentialGroup()
                        .addGroup(BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BiseccionPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(BiseccionPLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(It_BI_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(Tol_BI_TF)
                                    .addComponent(B_BI_TF)
                                    .addComponent(A_BI_TF))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BiseccionPLayout.setVerticalGroup(
            BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiseccionPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(A_BI_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(B_BI_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Tol_BI_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BiseccionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(It_BI_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(BiseccionBt)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Biseccion", BiseccionP);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Lagrange");

        LagrangeBt.setText("Calcular Lagrange");
        LagrangeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LagrangeBtActionPerformed(evt);
            }
        });

        jLabel12.setText("X");

        jLabel13.setText("Y");

        x1_LagrangeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1_LagrangeTfActionPerformed(evt);
            }
        });

        x2_LagrangeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2_LagrangeTfActionPerformed(evt);
            }
        });

        x3_LagrangeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3_LagrangeTfActionPerformed(evt);
            }
        });

        x4_LagrangeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x4_LagrangeTfActionPerformed(evt);
            }
        });

        jLabel14.setText("Valor a Interpolar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(x2_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(y2_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(x1_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(y1_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(x3_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(y3_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(x4_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(y4_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(LagrangeBt)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(vit_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x1_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y1_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vit_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x2_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y2_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x3_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y3_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x4_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y4_LagrangeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(LagrangeBt)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lagrange", jPanel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Gauss-Jordan");

        GaussBt.setText("Calcular Gauss");
        GaussBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaussBtActionPerformed(evt);
            }
        });

        jLabel33.setText("Y");

        jLabel34.setText("Z");

        jLabel36.setText("X");

        x1_GJTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1_GJTfActionPerformed(evt);
            }
        });

        x2_GJTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2_GJTfActionPerformed(evt);
            }
        });

        x3_GJTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3_GJTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GaussBt)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel36)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(x2_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y2_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(x1_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y1_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(x3_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y3_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(z2_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(z1_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(z3_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(123, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(GaussBt)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel36)
                                .addComponent(jLabel33))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(x1_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(y1_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(x2_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(y2_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(x3_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(y3_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(z1_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(z2_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(z3_GJTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(81, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Gauss", jPanel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Derivacion");

        DerivacionBt.setText("Calcular Derivada");
        DerivacionBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerivacionBtActionPerformed(evt);
            }
        });

        jLabel15.setText("X");

        jLabel16.setText("Y");

        jLabel17.setText("Valor a Derivar:");

        x1_DerivacionTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1_DerivacionTf1ActionPerformed(evt);
            }
        });

        x2_DerivacionTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2_DerivacionTf1ActionPerformed(evt);
            }
        });

        x3_DerivacionTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3_DerivacionTf1ActionPerformed(evt);
            }
        });

        x4_DerivacionTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x4_DerivacionTf1ActionPerformed(evt);
            }
        });

        x5_DerivacionTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x5_DerivacionTf1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(165, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(DerivacionBt)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(VD_Derivacion_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel15)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(x2_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y2_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(x1_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y1_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(x3_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y3_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(x4_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y4_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(x5_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y5_DerivacionTf5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(30, 30, 30)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(VD_Derivacion_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(DerivacionBt)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x1_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y1_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x2_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y2_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x3_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y3_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x4_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y4_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x5_DerivacionTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y5_DerivacionTf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Derivacion", jPanel4);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Integracion");

        IntegracionBt.setText("Calcular Integral");
        IntegracionBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntegracionBtActionPerformed(evt);
            }
        });

        jLabel18.setText("Limite Inferior");

        jLabel19.setText("Limite Superior");

        LI_IntegracionTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LI_IntegracionTf2ActionPerformed(evt);
            }
        });

        jLabel32.setText("Particiones");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 145, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(IntegracionBt)))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LI_IntegracionTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LS_IntegracionTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Part_IntegracionTf3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel32))
                        .addGap(34, 34, 34))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LS_IntegracionTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LI_IntegracionTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(IntegracionBt))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Part_IntegracionTf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Integracion", jPanel5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Newton");

        NewtonBt.setText("Calcular Newton");
        NewtonBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewtonBtActionPerformed(evt);
            }
        });

        jLabel21.setText("Tolerancia:");

        jLabel22.setText("X0:");

        jLabel23.setText("Iteraciones:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(164, Short.MAX_VALUE)
                        .addComponent(NewtonBt))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(It_NewtonTf, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(X0_NewtonTf)
                                    .addComponent(Tol_NewtonTf))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Tol_NewtonTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(X0_NewtonTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(It_NewtonTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(NewtonBt)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Newton", jPanel6);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("LU");

        LUBt.setText("Calcular LU");
        LUBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LUBtActionPerformed(evt);
            }
        });

        jLabel24.setText("X");

        x1_LUTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1_LUTf2ActionPerformed(evt);
            }
        });

        x2_LUTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2_LUTf2ActionPerformed(evt);
            }
        });

        x3_LUTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3_LUTf2ActionPerformed(evt);
            }
        });

        jLabel25.setText("Y");

        jLabel26.setText("Z");

        jLabel27.setText("Terminos Ind");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LUBt))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel24)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(x2_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(y2_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(x1_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(y1_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(x3_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(y3_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(z2_LUTf4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(z1_LUTf4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(z3_LUTf4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ti2_LUTf3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ti1_LUTf3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ti3_LUTf3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(x1_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y1_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(x2_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y2_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(x3_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y3_LUTf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(z1_LUTf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(z2_LUTf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(z3_LUTf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(Ti1_LUTf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ti2_LUTf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ti3_LUTf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(LUBt)
                .addContainerGap())
        );

        jTabbedPane1.addTab("LU", jPanel7);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Interpolacion de Newton");

        x3_InterNewtonTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3_InterNewtonTf1ActionPerformed(evt);
            }
        });

        x4_InterNewtonTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x4_InterNewtonTf1ActionPerformed(evt);
            }
        });

        jLabel29.setText("X");

        x5_InterNewtonTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x5_InterNewtonTf1ActionPerformed(evt);
            }
        });

        jLabel30.setText("Y");

        x1_InterNewtonTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1_InterNewtonTf1ActionPerformed(evt);
            }
        });

        jLabel31.setText("Valor a Interpolar:");

        x2_InterNewtonTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2_InterNewtonTf1ActionPerformed(evt);
            }
        });

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Calcular)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel29)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(x2_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y2_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(x1_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y1_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(x3_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y3_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(x4_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y4_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(x5_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(y5_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel31)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(VI_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(30, 30, 30)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(Calcular)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(jLabel30)
                        .addComponent(jLabel31))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x1_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y1_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VI_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x2_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y2_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x3_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y3_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x4_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y4_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(x5_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(y5_InterNewtonTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Inter Newton", jPanel1);

        Archivo.setText("Archivo");

        AcercaDeMI.setText("Acerca de ");
        AcercaDeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeMIActionPerformed(evt);
            }
        });
        Archivo.add(AcercaDeMI);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Archivo.add(jMenuItem1);

        jMenuBar1.add(Archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AcercaDeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeMIActionPerformed
        // TODO add your handling code here:
        System.out.println("El usuario dio click en Acerca de..");
        JOptionPane acerca_de = new JOptionPane();
        acerca_de.showMessageDialog(acerca_de, "Este programa fue hecho por:"+
                "\n\t-Juan Pablo Flores.\n\t-Luis Javier Chibras");
    }//GEN-LAST:event_AcercaDeMIActionPerformed

    private void BiseccionBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiseccionBtActionPerformed
        // TODO add your handling code here:
        float a,b,tol=0;
        double res;
        int it;
        System.out.println("Calculando Biseccion\n");
        a= Float.parseFloat(A_BI_TF.getText());
        b= Float.parseFloat(B_BI_TF.getText());
        it = Integer.parseInt(It_BI_TF.getText());
        tol = Float.parseFloat(Tol_BI_TF.getText());
        
        System.out.println("Los datos que ingreso el usuario son:\n");
        System.out.println("\ta: "+a+"\n\tb: "+b+ "\n\t tol: "+tol+"\n\t it: "+
                it);
        Biseccion Bis = new Biseccion(a, b, it, tol);
        res=Bis.BiseccionM();
        JOptionPane BisJP = new JOptionPane();
        BisJP.showMessageDialog(BisJP, "El resultado es:\n"+res);
        System.out.println("Finished");
        
    }//GEN-LAST:event_BiseccionBtActionPerformed

    private void LagrangeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LagrangeBtActionPerformed
        // TODO add your handling code here:
        double x1,x2,x3,x4,x5,y1,y2,y3,y4,y5,res;
        double vit=0;
        System.out.println("Calculando Lagrange\n");
        
        x1=Double.parseDouble(x1_LagrangeTf.getText());
        x2=Double.parseDouble(x2_LagrangeTf.getText());
        x3=Double.parseDouble(x3_LagrangeTf.getText());
        x4=Double.parseDouble(x4_LagrangeTf.getText());
        
        y1=Double.parseDouble(y1_LagrangeTf.getText());
        y2=Double.parseDouble(y2_LagrangeTf.getText());
        y3=Double.parseDouble(y3_LagrangeTf.getText());
        y4=Double.parseDouble(y4_LagrangeTf.getText());
        vit=Double.parseDouble(vit_LagrangeTf.getText());
        
        Lagrange LA = new Lagrange();
        res=LA.MetodoLagrange(x1, x2, x3, x4, y4, y3, y2, y1, vit);
        JOptionPane LAJP = new JOptionPane();
        LAJP.showMessageDialog(LAJP, "El resultado es:\n"+res);
        System.out.println("Finished");
    }//GEN-LAST:event_LagrangeBtActionPerformed

    private void A_BI_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BI_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_BI_TFActionPerformed

    private void x1_LagrangeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1_LagrangeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1_LagrangeTfActionPerformed

    private void x2_LagrangeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2_LagrangeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2_LagrangeTfActionPerformed

    private void x3_LagrangeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3_LagrangeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x3_LagrangeTfActionPerformed

    private void x4_LagrangeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x4_LagrangeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x4_LagrangeTfActionPerformed

    private void x1_DerivacionTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1_DerivacionTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1_DerivacionTf1ActionPerformed

    private void x2_DerivacionTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2_DerivacionTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2_DerivacionTf1ActionPerformed

    private void x3_DerivacionTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3_DerivacionTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x3_DerivacionTf1ActionPerformed

    private void x4_DerivacionTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x4_DerivacionTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x4_DerivacionTf1ActionPerformed

    private void x5_DerivacionTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x5_DerivacionTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x5_DerivacionTf1ActionPerformed

    private void x1_LUTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1_LUTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1_LUTf2ActionPerformed

    private void x2_LUTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2_LUTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2_LUTf2ActionPerformed

    private void x3_LUTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3_LUTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x3_LUTf2ActionPerformed

    private void x3_InterNewtonTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3_InterNewtonTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x3_InterNewtonTf1ActionPerformed

    private void x4_InterNewtonTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x4_InterNewtonTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x4_InterNewtonTf1ActionPerformed

    private void x5_InterNewtonTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x5_InterNewtonTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x5_InterNewtonTf1ActionPerformed

    private void x1_InterNewtonTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1_InterNewtonTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1_InterNewtonTf1ActionPerformed

    private void x2_InterNewtonTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2_InterNewtonTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2_InterNewtonTf1ActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        System.out.println("Calculando Interpolacion de Newton\n");
        double a[][] = new double[5][2];
        double vip,res;
        //ingresamos los valores de x que estan en la componente grafica
        a[0][0]=Double.parseDouble(x1_InterNewtonTf1.getText());
        a[1][0]=Double.parseDouble(x2_InterNewtonTf1.getText());
        a[2][0]=Double.parseDouble(x3_InterNewtonTf1.getText());
        a[3][0]=Double.parseDouble(x4_InterNewtonTf1.getText());
        a[4][0]=Double.parseDouble(x5_InterNewtonTf1.getText());
        
        //ingresamos los valores de y
        a[0][1]=Double.parseDouble(y1_InterNewtonTf1.getText());
        a[1][1]=Double.parseDouble(y2_InterNewtonTf1.getText());
        a[2][1]=Double.parseDouble(y3_InterNewtonTf1.getText());
        a[3][1]=Double.parseDouble(y4_InterNewtonTf1.getText());
        a[4][1]=Double.parseDouble(y5_InterNewtonTf1.getText());
        
        //ingresamos el valor a interpolar
        vip=Double.parseDouble(VI_InterNewtonTf1.getText());
        
        MetodoIPNewton ipn = new MetodoIPNewton();
        res=ipn.MetodoInterNewton(a, vip);
        
        JOptionPane ipnJP = new JOptionPane();
        ipnJP.showMessageDialog(ipnJP, "El resultado es: "+res);
        System.out.println("Done!");
    }//GEN-LAST:event_CalcularActionPerformed

    private void GaussBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaussBtActionPerformed
        // TODO add your handling code here:
        System.out.println("Calculando Gauss\n");
        double a[][] = new double[3][3];
        
        
        a[0][0]=Double.parseDouble(x1_GJTf.getText());
        a[0][1]=Double.parseDouble(x2_GJTf.getText());
        a[0][2]=Double.parseDouble(x3_GJTf.getText());
        a[1][0]=Double.parseDouble(y1_GJTf.getText());
        a[1][1]=Double.parseDouble(y2_GJTf.getText());
        a[1][2]=Double.parseDouble(y3_GJTf.getText());
        a[2][0]=Double.parseDouble(z1_GJTf.getText());
        a[2][1]=Double.parseDouble(z2_GJTf.getText());
        a[2][2]=Double.parseDouble(z3_GJTf.getText());
        
        GaussJordan gj = new GaussJordan();
        double ans[]=gj.MetodoGaussJordan(a);
        
        
        JOptionPane gjJP = new JOptionPane();
        gjJP.showMessageDialog(gjJP, "Los resultados son: \n\t1. "+ans[0]+
                "\n\t2. "+ans[1]+"\n\t3. "+ans[2]);
        System.out.println("Done!");
    }//GEN-LAST:event_GaussBtActionPerformed

    private void DerivacionBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerivacionBtActionPerformed
        // TODO add your handling code here:
        System.out.println("Calculando Derivada\n");
        double x1,x2,x3,x4,x5,y1,y2,y3,y4,y5;
        double vit=0;
        System.out.println("Calculando Lagrange\n");
        
        x1=Double.parseDouble(x1_DerivacionTf1.getText());
        x2=Double.parseDouble(x2_DerivacionTf1.getText());
        x3=Double.parseDouble(x3_DerivacionTf1.getText());
        x4=Double.parseDouble(x4_DerivacionTf1.getText());
        x5=Double.parseDouble(x5_DerivacionTf1.getText());
        
        y1=Double.parseDouble(y1_DerivacionTf1.getText());
        y2=Double.parseDouble(y2_DerivacionTf1.getText());
        y3=Double.parseDouble(y3_DerivacionTf1.getText());
        y4=Double.parseDouble(y4_DerivacionTf1.getText());
        y5=Double.parseDouble(y5_DerivacionTf5.getText());
        vit=Double.parseDouble(VD_Derivacion_Tf.getText());
        
        DerivacionNumerica dn= new DerivacionNumerica();
        double[] res=dn.Derivacion(x1, x2, x3, x4, x5, y5, y4, y3, y2, y1, vit);
       
        JOptionPane DerJP = new JOptionPane();
        DerJP.showMessageDialog(DerJP, "La Diferencia Centrada es: "+res[0]+
                "\nLa Diferencia Atras es: "+res[1]+ "\n La Diferencia Adelante es:"+
                res[2]);
        System.out.println("Finished");
        
    }//GEN-LAST:event_DerivacionBtActionPerformed

    private void NewtonBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewtonBtActionPerformed
        // TODO add your handling code here:
        System.out.println("Calculando Newton\n");
        double tol,X0,res;
        int it;
        
        tol=Double.parseDouble(Tol_NewtonTf.getText());
        X0=Double.parseDouble(X0_NewtonTf.getText());
        it=Integer.parseInt(It_NewtonTf.getText());
        
        Newton nt = new Newton(tol, X0, it);
        res=nt.calculaRaiz();
        
          JOptionPane ntJP = new JOptionPane();
        ntJP.showMessageDialog(ntJP, "El resultado es: "+ res);
        
        
        System.out.println("Done!");
    }//GEN-LAST:event_NewtonBtActionPerformed

    private void LUBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LUBtActionPerformed
        // TODO add your handling code here:
        System.out.println("Calculando LU\n");
        double a[][] = new double[3][3], b[]= new double [3];
        a[0][0]= Double.parseDouble(x1_LUTf2.getText());
        a[1][0]= Double.parseDouble(x2_LUTf2.getText());
        a[2][0]= Double.parseDouble(x3_LUTf2.getText());
        a[0][1]= Double.parseDouble(y1_LUTf2.getText());
        a[1][1]= Double.parseDouble(y2_LUTf2.getText());
        a[2][1]= Double.parseDouble(y3_LUTf2.getText());
        a[0][2]= Double.parseDouble(z1_LUTf4.getText());
        a[1][2]= Double.parseDouble(z2_LUTf4.getText());
        a[2][2]= Double.parseDouble(z3_LUTf4.getText());
        
        b[0]= Double.parseDouble(Ti1_LUTf3.getText());                
        b[1]= Double.parseDouble(Ti2_LUTf3.getText());   
        b[2]= Double.parseDouble(Ti3_LUTf3.getText());   
        
        MetodoLU lu = new MetodoLU();
        double[] res = lu.MetodoLu(a, b);
        
        JOptionPane luJP = new JOptionPane();
        luJP.showMessageDialog(luJP, "El resultado es: \n\t1. "+ res[0]+
                "\n\t2. "+ res[1]+ "\n\t3. "+res[2]);
        System.out.println("Done!");
    }//GEN-LAST:event_LUBtActionPerformed

    private void It_BI_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_It_BI_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_It_BI_TFActionPerformed

    private void LI_IntegracionTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LI_IntegracionTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LI_IntegracionTf2ActionPerformed

    private void IntegracionBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntegracionBtActionPerformed
        // TODO add your handling code here:
        System.out.println("Calculando Integral\n");
        double LS, LI,res;
        int P;
        LS= Double.parseDouble(LS_IntegracionTf2.getText());
        LI= Double.parseDouble(LI_IntegracionTf2.getText());
        P = Integer.parseInt(Part_IntegracionTf3.getText());
        
        IntegracionNumerica in = new IntegracionNumerica(LI, LS, P);
        res = in.integral();
        
         JOptionPane inJP = new JOptionPane();
        inJP.showMessageDialog(inJP," La integral es: "+res);
        System.out.println("Done!");
    }//GEN-LAST:event_IntegracionBtActionPerformed

    private void x1_GJTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1_GJTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1_GJTfActionPerformed

    private void x2_GJTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2_GJTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2_GJTfActionPerformed

    private void x3_GJTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3_GJTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x3_GJTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A_BI_TF;
    private javax.swing.JMenuItem AcercaDeMI;
    private javax.swing.JMenu Archivo;
    private javax.swing.JTextField B_BI_TF;
    private javax.swing.JButton BiseccionBt;
    private javax.swing.JPanel BiseccionP;
    private javax.swing.JButton Calcular;
    private javax.swing.JButton DerivacionBt;
    private javax.swing.JButton GaussBt;
    private javax.swing.JButton IntegracionBt;
    private javax.swing.JTextField It_BI_TF;
    private javax.swing.JTextField It_NewtonTf;
    private javax.swing.JTextField LI_IntegracionTf2;
    private javax.swing.JTextField LS_IntegracionTf2;
    private javax.swing.JButton LUBt;
    private javax.swing.JButton LagrangeBt;
    private javax.swing.JButton NewtonBt;
    private javax.swing.JTextField Part_IntegracionTf3;
    private javax.swing.JTextField Ti1_LUTf3;
    private javax.swing.JTextField Ti2_LUTf3;
    private javax.swing.JTextField Ti3_LUTf3;
    private javax.swing.JTextField Tol_BI_TF;
    private javax.swing.JTextField Tol_NewtonTf;
    private javax.swing.JTextField VD_Derivacion_Tf;
    private javax.swing.JTextField VI_InterNewtonTf1;
    private javax.swing.JTextField X0_NewtonTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField vit_LagrangeTf;
    private javax.swing.JTextField x1_DerivacionTf1;
    private javax.swing.JTextField x1_GJTf;
    private javax.swing.JTextField x1_InterNewtonTf1;
    private javax.swing.JTextField x1_LUTf2;
    private javax.swing.JTextField x1_LagrangeTf;
    private javax.swing.JTextField x2_DerivacionTf1;
    private javax.swing.JTextField x2_GJTf;
    private javax.swing.JTextField x2_InterNewtonTf1;
    private javax.swing.JTextField x2_LUTf2;
    private javax.swing.JTextField x2_LagrangeTf;
    private javax.swing.JTextField x3_DerivacionTf1;
    private javax.swing.JTextField x3_GJTf;
    private javax.swing.JTextField x3_InterNewtonTf1;
    private javax.swing.JTextField x3_LUTf2;
    private javax.swing.JTextField x3_LagrangeTf;
    private javax.swing.JTextField x4_DerivacionTf1;
    private javax.swing.JTextField x4_InterNewtonTf1;
    private javax.swing.JTextField x4_LagrangeTf;
    private javax.swing.JTextField x5_DerivacionTf1;
    private javax.swing.JTextField x5_InterNewtonTf1;
    private javax.swing.JTextField y1_DerivacionTf1;
    private javax.swing.JTextField y1_GJTf;
    private javax.swing.JTextField y1_InterNewtonTf1;
    private javax.swing.JTextField y1_LUTf2;
    private javax.swing.JTextField y1_LagrangeTf;
    private javax.swing.JTextField y2_DerivacionTf1;
    private javax.swing.JTextField y2_GJTf;
    private javax.swing.JTextField y2_InterNewtonTf1;
    private javax.swing.JTextField y2_LUTf2;
    private javax.swing.JTextField y2_LagrangeTf;
    private javax.swing.JTextField y3_DerivacionTf1;
    private javax.swing.JTextField y3_GJTf;
    private javax.swing.JTextField y3_InterNewtonTf1;
    private javax.swing.JTextField y3_LUTf2;
    private javax.swing.JTextField y3_LagrangeTf;
    private javax.swing.JTextField y4_DerivacionTf1;
    private javax.swing.JTextField y4_InterNewtonTf1;
    private javax.swing.JTextField y4_LagrangeTf;
    private javax.swing.JTextField y5_DerivacionTf5;
    private javax.swing.JTextField y5_InterNewtonTf1;
    private javax.swing.JTextField z1_GJTf;
    private javax.swing.JTextField z1_LUTf4;
    private javax.swing.JTextField z2_GJTf;
    private javax.swing.JTextField z2_LUTf4;
    private javax.swing.JTextField z3_GJTf;
    private javax.swing.JTextField z3_LUTf4;
    // End of variables declaration//GEN-END:variables
}
